FROM quay.io/centos-bootc/centos-bootc:stream10 as builder

RUN rm -rf /etc/yum.repos.d/*
COPY rocky-10.repo /etc/yum.repos.d

COPY rocky-10.yaml /usr/share/doc/bootc-base-imagectl/manifests

RUN /usr/libexec/bootc-base-imagectl build-rootfs --manifest=rocky-10 /target-rootfs

FROM scratch

COPY --from=builder /target-rootfs/ /

LABEL containers.bootc 1
LABEL ostree.bootable 1

ENV container=oci

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
